apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    config.kubernetes.io/function: |
      container:
        image: squaremo/flux-helm-chart
data:
  releaseName: flux
  namespace: flux-system
  values: |
    git:
      readonly: true
    registry:
      disableScanning: true
