apiVersion: rbac.authorization.k8s.io/v1beta1 # Source: flux/templates/rbac.yaml
kind: ClusterRoleBinding
metadata:
  name: fluxcdflux
  labels:
    app: flux
    chart: flux-1.3.0
    release: fluxcdflux
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluxcdflux
subjects:
- name: fluxcdflux
  namespace: "flux-system"
  kind: ServiceAccount
