apiVersion: rbac.authorization.k8s.io/v1beta1 # Source: flux/templates/rbac.yaml
kind: ClusterRoleBinding
metadata:
  name: flux
  labels:
    app: flux
    chart: flux-1.3.0
    release: flux
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flux
subjects:
- name: flux
  namespace: "flux-system"
  kind: ServiceAccount
