apiVersion: rbac.authorization.k8s.io/v1beta1 # Source: flux/templates/rbac.yaml
kind: ClusterRole
metadata:
  name: flux
  labels:
    app: flux
    chart: flux-1.3.0
    release: flux
    heritage: Helm
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
