apiVersion: apps/v1 # Source: flux/templates/deployment.yaml
kind: Deployment
metadata:
  name: fluxcdflux
  labels:
    app: flux
    chart: flux-1.3.0
    release: fluxcdflux
    heritage: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flux
      release: fluxcdflux
  template:
    metadata:
      annotations:
      labels:
        app: flux
        release: fluxcdflux
    spec:
      serviceAccountName: fluxcdflux
      volumes:
      - name: kubedir
        configMap:
          name: fluxcdflux-kube-config
      - name: git-key
        secret:
          secretName: fluxcdflux-git-deploy
          defaultMode: 0400
      - name: git-keygen
        emptyDir:
          medium: Memory
      containers:
      - name: flux
        image: "docker.io/fluxcd/flux:1.19.0"
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 3030
          protocol: TCP
        livenessProbe:
          httpGet:
            port: 3030
            path: /api/flux/v6/identity.pub
          initialDelaySeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            port: 3030
            path: /api/flux/v6/identity.pub
          initialDelaySeconds: 5
          timeoutSeconds: 5
        volumeMounts:
        - name: kubedir
          mountPath: /root/.kubectl
        - name: git-key
          mountPath: /etc/fluxd/ssh
          readOnly: true
        - name: git-keygen
          mountPath: /var/fluxd/keygen
        env:
        - name: KUBECONFIG
          value: /root/.kubectl/config
        args:
        - --log-format=fmt
        - --ssh-keygen-dir=/var/fluxd/keygen
        - --ssh-keygen-format=RFC4716
        - --k8s-secret-name=fluxcdflux-git-deploy
        - --memcached-hostname=fluxcdflux-memcached
        - --sync-state=git
        - --memcached-service=
        - --git-url=
        - --git-branch=master
        - --git-path=
        - --git-readonly=true
        - --git-user=Weave Flux
        - --git-email=support@weave.works
        - --git-verify-signatures=false
        - --git-set-author=false
        - --git-poll-interval=5m
        - --git-timeout=20s
        - --sync-interval=5m
        - --git-ci-skip=false
        - --automation-interval=5m
        - --registry-rps=200
        - --registry-burst=125
        - --registry-trace=false
        - --registry-disable-scanning
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
      nodeSelector:
        beta.kubernetes.io/os: linux
