apiVersion: v1 # Source: flux/templates/service.yaml
kind: Service
metadata:
  name: fluxcdflux
  labels:
    app: flux
    chart: flux-1.3.0
    release: fluxcdflux
    heritage: Helm
spec:
  type: ClusterIP
  ports:
  - port: 3030
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: flux
    release: fluxcdflux
